version: "3.8"

services:
  python-app:
    container_name: python-app
    image: 34.121.95.79:5000/pythonapp:latest   # <- your private registry image here
    ports:
      - "5000:5000"
    environment:
      - APP_NAME=Python Testing App
      - APP_VERSION=1.1.0
      - ENVIRONMENT=staging

